spring:
  application:
    name: config-client-demo
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

coffee:
  special: double espresso

---
spring:
  config:
    activate:
      on-cloud-platform: cloud_foundry
  cloud:
    config:
      enabled: true
      import-check:
        enabled: false
logging:
  level:
    org.springframework.cloud.config: debug